import turtle
import math

sun=turtle.Pen()
sun.shape('circle')
sun.shapesize(1)
sun.fillcolor('red')

mercury=turtle.Pen()
mercury.pu()
mercury.setpos(0,-20)
mercury.pd()
mercury.shape('circle')
mercury.shapesize(0.1)
mercury.pensize(0.01)
mercury.pencolor('blue')
mercury.fillcolor('blue')
mercury.speed(0)

venus=turtle.Pen()
venus.pu()
venus.setpos(0,-40)
venus.pd()
venus.shape('circle')
venus.shapesize(0.4)
venus.pensize(0.01)
venus.pencolor('yellow')
venus.fillcolor('yellow')
venus.speed(0)

earth=turtle.Pen()
earth.pu()
earth.setpos(0,-90)
earth.pd()
earth.shape('circle')
earth.shapesize(1)
earth.pensize(0.01)
earth.pencolor('green')
earth.fillcolor('green')
earth.speed(0)

mars=turtle.Pen()
mars.pu()
mars.setpos(0,-120)
mars.pd()
mars.shape('circle')
mars.shapesize(0.6)
mars.pensize(0.01)
mars.pencolor('red')
mars.fillcolor('red')
mars.speed(0)

jupiter=turtle.Pen()
jupiter.pu()
jupiter.setpos(0,-180)
jupiter.pd()
jupiter.shape('circle')
jupiter.shapesize(2)
jupiter.pensize(0.01)
jupiter.pencolor('grey')
jupiter.fillcolor('grey')
jupiter.speed(0)

satan=turtle.Pen()
satan.pu()
satan.setpos(0,-240)
satan.pd()
satan.shape('circle')
satan.shapesize(1.9)
satan.pensize(0.01)
satan.pencolor('brown')
satan.fillcolor('brown')
satan.speed(0)

while True:
    mercury.circle(20,5)
    venus.circle(40,4)
    earth.circle(90,3)
    mars.circle(120,2)
    jupiter.circle(180,1.5)
    satan.circle(240,1)
	
	

